[package]
name = "storage-client"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
serde = { workspace = true }

bcs = { workspace = true }
mango-crypto = { workspace = true }
mango-logger ={ workspace = true }
mango-infallible = { workspace = true }
mango-secure-net = { workspace = true }
mango-types = { workspace = true }

storage-interface = { workspace = true }

