[package]
name = "mango-events-fetcher"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow ={ workspace = true }
hex ={ workspace = true }
reqwest = { workspace = true }
structopt ={ workspace = true }
futures ={ workspace = true }
tokio ={ workspace = true }


mango-client = { workspace = true }
mango-types = { workspace = true }
bcs = { workspace = true }
