[package]
name = "mango-framework-releases"
version = "0.1.0"
edition = "2018"


[dependencies]
move-command-line-common = { workspace=true }
mango-crypto = { workspace=true }
mango-types = { workspace=true }

move-binary-format = { workspace=true }

anyhow ={ workspace = true }
include_dir = { workspace = true }
bcs = { workspace = true }
once_cell  = { workspace = true }

[dev-dependencies]
move-bytecode-verifier = { workspace = true }
