[package]
name = "jsonrpc-integration-tests"
version = "0.0.0"


license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
bcs = { workspace = true }
hex ={ workspace = true }
reqwest = { workspace = true }
serde_json ={ workspace = true }

mango-json-rpc-types = { workspace = true }
mango-sdk  = { workspace = true }



[[test]]
name = "jsonrpc-forge"
harness = false
