[package]
name = "mango-operational-tool"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
base64 ={ workspace = true }
futures ={ workspace = true }
hex ={ workspace = true }
itertools ={ workspace = true }
rand = { workspace = true }
serde ={ workspace = true }
serde_json ={ workspace = true }
serde_yaml ={ workspace = true }
structopt ={ workspace = true }
thiserror ={ workspace = true }
tokio ={ workspace = true }
tokio-util ={ workspace = true }
toml ={ workspace = true }

bcs = { workspace = true }
mango-client ={ workspace = true }
mango-config ={ workspace = true }
mango-crypto = { workspace = true }
mango-global-constants= { workspace = true }
mango-infallible ={ workspace = true }
mango-management = { path = ".." }
mango-network-address-encryption = { workspace = true }
mango-secure-storage = { workspace = true }
mango-types = { workspace = true }

mango-temppath ={ workspace = true }
fallible ={ workspace = true }
netcore ={ workspace = true }
network ={ workspace = true }
mango-transaction-builder ={ workspace = true }


