[package]
name = "swiss-knife"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt ={ workspace = true }
rand = { workspace = true }
hex ={ workspace = true }
serde_json ={ workspace = true }
serde = { workspace = true }

bcs = { workspace = true }
mango-types = { workspace = true }
mango-crypto = { workspace = true }

move-core-types = { workspace = true }
mango-transaction-builder ={ workspace = true }
