[package]
name = "move-oncall-trainer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow ={ workspace = true }
structopt ={ workspace = true }
tempfile = { workspace = true }
nix = { workspace = true }
rand = { workspace = true }
rustyline = { workspace = true }
gag = { workspace = true }
bcs = { workspace = true }

cli = { workspace = true }
mango-client = { workspace = true }
mango-config = { workspace = true }
mango-framework-releases = { workspace = true }
mango-genesis-tool = { workspace = true }
mango-json-rpc-types = { workspace = true }
mango-types = { workspace = true }
mango-node = { workspace = true }
mango-temppath ={ workspace = true }
