[package]
name = "mango-json-rpc-types"
version = "0.0.2"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
hex ={ workspace = true }
serde = { workspace = true }
serde_json ={ workspace = true }

mango-types = { workspace = true }
bcs = { workspace = true }
mango-crypto = { workspace = true }
mango-transaction-builder = { workspace = true }
move-core-types = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
thiserror ={ workspace = true }

[dev-dependencies]
