[package]
name = "diemsum"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
structopt ={ workspace = true }
serde = { workspace = true }
serde_json ={ workspace = true }

diemdb = { workspace = true }
mango-crypto = { workspace = true }
mango-types = { workspace = true }

storage-interface = { workspace = true }
