[package]
name = "mango-github-client"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { workspace = true }
serde_json ={ workspace = true }
thiserror ={ workspace = true }
ureq = { workspace = true, features = ["json"] }
proxy = { workspace = true }

[dev-dependencies]
base64 ={ workspace = true }
