[package]
name = "netcore"
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = { workspace = true }
futures ={ workspace = true }
pin-project = { workspace = true }
serde = { workspace = true }
tokio ={ workspace = true }
tokio-util ={ workspace = true }
url = { workspace = true }


mango-types = { workspace = true }
memsocket = { workspace = true }
proxy = { workspace = true }

[dev-dependencies]
mango-logger ={ workspace = true }
memsocket = { workspace = true }

