[package]
name = "schemadb"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
once_cell  = { workspace = true }
mango-config = { workspace = true }
mango-logger ={ workspace = true }
mango-metrics = { workspace = true }


[dependencies.rocksdb]
version = "0.19.0"
default-features = false
features = ["lz4"]

[dev-dependencies]
byteorder  = { workspace = true }
proptest  = { workspace = true }
mango-temppath ={ workspace = true }
