[package]
name = "executor-test-helpers"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }

executor = { workspace = true }
executor-types = { workspace = true }
diemdb = { workspace = true }
mango-config = { workspace = true }
mango-crypto = { workspace = true }
mango-genesis-tool = { workspace = true }
mango-temppath ={ workspace = true }
mango-types = { workspace = true }
mango-vm = { workspace = true }

storage-interface = { workspace = true }
storage-service = { workspace = true }
mango-transaction-builder ={ workspace = true }
vm-genesis = { workspace = true }
