[package]
name = "mango-secure-storage"
version = "0.1.0"

description = "mango's Persistent, Secure Storage"

license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
base64 ={ workspace = true }
chrono  = { workspace = true }
enum_dispatch = { workspace = true }
rand = { workspace = true }
serde ={ workspace = true }
serde_json ={ workspace = true }
thiserror ={ workspace = true }

bcs = { workspace = true }
mango-crypto = { workspace = true }
mango-github-client = { workspace = true }
mango-infallible = { workspace = true }
mango-logger = { workspace = true }
mango-temppath = { workspace = true }
mango-time-service = { workspace = true }
mango-vault-client = { workspace = true }


[dev-dependencies]
mango-crypto = { workspace = true }
mango-crypto-derive = { workspace = true }
rand = { workspace = true }


