[package]
name = "offchain"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = { workspace = true }
bech32 = { workspace = true }
hex ={ workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
thiserror ={ workspace = true }
url = { workspace = true }
uuid = { workspace = true }

mango-sdk = { workspace = true }

[dev-dependencies]
rand_core = { workspace = true }
rstest = { workspace = true }


