[package]
name = "mango-jellyfish-merkle"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
byteorder  = { workspace = true }
itertools = { workspace = true }
mirai-annotations ={ workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
once_cell  = { workspace = true }
proptest  = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror ={ workspace = true }

bcs = { workspace = true }
mango-crypto = { workspace = true }
mango-crypto-derive = { workspace = true }
mango-infallible = { workspace = true }
mango-metrics = { workspace = true }
mango-types = { workspace = true }


[dev-dependencies]
rand = { workspace = true }
proptest  = { workspace = true }
proptest-derive  = { workspace = true }

mango-crypto = { workspace = true }
mango-types ={ workspace = true }

