[package]
name = "diemdb"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
arc-swap = { workspace = true }
byteorder  = { workspace = true }
itertools ={ workspace = true }
once_cell  = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
proptest  = { workspace = true }
proptest-derive = { workspace = true }
serde = { workspace = true }
thiserror ={ workspace = true }

accumulator = { workspace = true }
bcs = { workspace = true }
mango-config = { workspace = true }
mango-crypto = { workspace = true }
mango-jellyfish-merkle = { workspace = true }
mango-logger ={ workspace = true }
mango-metrics = { workspace = true }
mango-infallible = { workspace = true }
mango-proptest-helpers = { workspace = true }
mango-temppath = { workspace = true }
mango-types = { workspace = true }

move-core-types = { workspace = true }

num-variants = { workspace = true }
schemadb = { workspace = true }
storage-interface = { workspace = true }

[dev-dependencies]
proptest  = { workspace = true }
proptest-derive  = { workspace = true }
rand = { workspace = true }

mango-temppath ={ workspace = true }

mango-jellyfish-merkle = { workspace = true }
mango-proptest-helpers = { workspace = true }

