[package]
name = "backup-service"
version = "0.1.0"


license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow ={ workspace = true }
bytes = { workspace = true }
futures ={ workspace = true }
hyper = { workspace = true }
once_cell  = { workspace = true }
serde = { workspace = true }
tokio ={ workspace = true }
warp = { workspace = true }

bcs = { workspace = true }
mango-crypto = { workspace = true }
mango-logger = { workspace = true }
mango-metrics = { workspace = true }
mango-types = { workspace = true }

diemdb = { workspace = true }
storage-interface = { workspace = true }

[dev-dependencies]
mango-config = { workspace = true }
mango-temppath ={ workspace = true }

reqwest = { workspace = true }

