[package]
name = "mango-log-derive"
version = "0.1.0"


license = "Apache-2.0"
publish = false
edition = "2018"

[lib]
proc-macro = true

[dependencies]

syn   = { workspace = true }
quote  = { workspace = true }
proc-macro2  = { workspace = true }
