[package]
name = "mango-vault-client"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 ={ workspace = true }
chrono  = { workspace = true }
once_cell  = { workspace = true }
proptest  = { workspace = true }
native-tls = { workspace = true }
serde = { workspace = true }
serde_json ={ workspace = true }
thiserror ={ workspace = true }
ureq = { workspace = true }

mango-crypto = { workspace = true }
mango-proptest-helpers = { workspace = true }
mango-types = { workspace = true }


[dev-dependencies]
proptest  = { workspace = true }
mango-types = { workspace = true }


