[package]
name = "mango-writeset-generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow ={ workspace = true }
structopt ={ workspace = true }
tempfile = { workspace = true }
handlebars = { workspace = true }
serde = { workspace = true }
serde_json ={ workspace = true }
once_cell  = { workspace = true }

move-bytecode-verifier = { workspace = true }

mango-crypto-derive = { workspace = true }
mango-crypto = { workspace = true }
mango-types = { workspace = true }
mango-framework-releases = { workspace = true }
mango-framework = { workspace = true }
move-compiler = { workspace = true }
bcs = { workspace = true }
mango-state-view = { workspace = true }
mango-validator-interface = { workspace = true }
mango-transaction-replay = { workspace = true }
diemdb ={ workspace = true }
mango-vm = { workspace = true }
move-binary-format = { workspace = true }
move-vm-types = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
